using SqlBuildingBlocks.LogicalEntities;
using SqlBuildingBlocks.POCOs;
using System.Data;

namespace SqlBuildingBlocks.QueryProcessing;

internal class ProcessingState
{

    /// <summary>
    /// Table in the processing chain where the WHERE statement can be evaluated. (i.e. all of the columns referenced in the WHERE condition can have values to evaluate)
    /// </summary>
    public SqlTable? WhereApplied { get; set; }

    /// <summary>
    /// Set of Tables in the FROM/JOIN chains that have or are int the process of being processed.
    /// Issue #183: keyed by <see cref="SqlTableOccurrenceComparer"/> so two distinct occurrences of the
    /// same table (e.g., a self-join with aliases <c>a</c> and <c>b</c>) remain distinct entries.
    /// </summary>
    public HashSet<SqlTable> TablesInProcessing = new(SqlTableOccurrenceComparer.Instance);

    /// <summary>
    /// A Table keyed mapping of DataTables that only contain the columns which will be needed for this query.  It limits the amount
    /// of data to be generated by projecting only those columns into the DataRows.
    /// Issue #183: alias-aware key so per-occurrence projections do not collide on a self-join.
    /// </summary>
    public Dictionary<SqlTable, DataTable> TablesProjections = new(SqlTableOccurrenceComparer.Instance);

    /// <summary>
    /// Issue #183: alias-aware key so each occurrence of a self-joined table has its own current-row
    /// substitute. Without this, the second occurrence overwrites the first and the JOIN ON predicate
    /// builder sees both columns as belonging to the same row, producing a Cartesian product.
    /// </summary>
    public Dictionary<SqlTable, DataRow> DataRowsOfOtherTables = new(SqlTableOccurrenceComparer.Instance);

    public VirtualDataTable QueryOutput = new("ResultSet");

    public bool HasAggregates { get; set; }

    /// <summary>
    /// Whether the SELECT contains window functions or window aggregates (OVER clause).
    /// </summary>
    public bool HasWindowFunctions { get; set; }

    /// <summary>
    /// For RIGHT/FULL OUTER JOIN: all rows from the join table, materialized for match tracking.
    /// Issue #183: alias-aware key.
    /// </summary>
    public Dictionary<SqlTable, List<DataRow>> AllJoinTableRows = new(SqlTableOccurrenceComparer.Instance);

    /// <summary>
    /// For RIGHT/FULL OUTER JOIN: tracks which rows in <see cref="AllJoinTableRows"/> have been matched.
    /// Issue #183: alias-aware key.
    /// </summary>
    public Dictionary<SqlTable, bool[]> MatchedJoinRows = new(SqlTableOccurrenceComparer.Instance);

    /// <summary>
    /// The current source DataRow being processed. Used by built-in function closures
    /// to access column values from the current row during iteration.
    /// </summary>
    public DataRow? CurrentSourceRow { get; set; }
}
